=== ipallares/ipt-exporter/src/exporter/application/services/exporter/schemas/cv-schema-v1.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "cv-input-v1",
    "type": "object",
    "title": "Schema to validate inputs for CVs",
    "required": [
        "personalDetails",
        "coverLetter",
        "workExperiences",
        "academicExperiences"
    ],
    "properties": {
        "personalDetails": {
            "$id": "#/properties/personalDetails",
            "type": "object",
            "required": [
                "name",
                "surname",
                "email",
                "phoneNumber"
            ],
            "properties": {
                "name": {
                    "$id": "#/properties/personalDetails/properties/name",
                    "type": "string"
                },
                "surname": {
                    "$id": "#/properties/personalDetails/properties/surname",
                    "type": "string"
                },
                "email": {
                    "$id": "#/properties/personalDetails/properties/email",
                    "type": "string"
                },
                "phoneNumber": {
                    "$id": "#/properties/personalDetails/properties/phoneNumber",
                    "type": "string"
                }
            },
            "additionalProperties": true
        },
        "coverLetter": {
            "$id": "#/properties/coverLetter",
            "type": "object",
            "required": [
                "text"
            ],
            "properties": {
                "text": {
                    "$id": "#/properties/coverLetter/properties/text",
                    "type": "string"
                }
            },
            "additionalProperties": true
        },
        "workExperiences": {
            "$id": "#/properties/workExperiences",
            "type": "array",
            "additionalItems": true,
            "items": {
                "$id": "#/properties/workExperiences/items",
                "anyOf": [
                    {
                        "$id": "#/properties/workExperiences/items/anyOf/0",
                        "type": "object",
                        "required": [
                            "workExperience"
                        ],
                        "properties": {
                            "workExperience": {
                                "$id": "#/properties/workExperiences/items/anyOf/0/properties/workExperience",
                                "type": "object",
                                "required": [
                                    "companyName",
                                    "position",
                                    "startDate",
                                    "endDate",
                                    "description"
                                ],
                                "properties": {
                                    "companyName": {
                                        "$id": "#/properties/workExperiences/items/anyOf/0/properties/workExperience/properties/companyName",
                                        "type": "string"
                                    },
                                    "position": {
                                        "$id": "#/properties/workExperiences/items/anyOf/0/properties/workExperience/properties/position",
                                        "type": "string"
                                    },
                                    "startDate": {
                                        "$id": "#/properties/workExperiences/items/anyOf/0/properties/workExperience/properties/startDate",
                                        "type": "string",
                                        "format": "date"

                                    },
                                    "endDate": {
                                        "$id": "#/properties/workExperiences/items/anyOf/0/properties/workExperience/properties/endDate",
                                        "type": "string",
                                        "format": "date"
                                    },
                                    "description": {
                                        "$id": "#/properties/workExperiences/items/anyOf/0/properties/workExperience/properties/description",
                                        "type": "string"
                                    }
                                },
                                "additionalProperties": true
                            }
                        },
                        "additionalProperties": true
                    }
                ]
            }
        },
        "academicExperiences": {
            "$id": "#/properties/academicExperiences",
            "type": "array",
            "additionalItems": true,
            "items": {
                "$id": "#/properties/academicExperiences/items",
                "anyOf": [
                    {
                        "$id": "#/properties/academicExperiences/items/anyOf/0",
                        "type": "object",
                        "required": [
                            "academicExperience"
                        ],
                        "properties": {
                            "academicExperience": {
                                "$id": "#/properties/academicExperiences/items/anyOf/0/properties/academicExperience",
                                "type": "object",
                                "required": [
                                    "schoolName",
                                    "title",
                                    "startDate",
                                    "endDate",
                                    "description"
                                ],
                                "properties": {
                                    "schoolName": {
                                        "$id": "#/properties/academicExperiences/items/anyOf/0/properties/academicExperience/properties/schoolName",
                                        "type": "string"
                                    },
                                    "title": {
                                        "$id": "#/properties/academicExperiences/items/anyOf/0/properties/academicExperience/properties/title",
                                        "type": "string"
                                    },
                                    "startDate": {
                                        "$id": "#/properties/academicExperiences/items/anyOf/0/properties/academicExperience/properties/startDate",
                                        "type": "string",
                                        "format": "date"
                                    },
                                    "endDate": {
                                        "$id": "#/properties/academicExperiences/items/anyOf/0/properties/academicExperience/properties/endDate",
                                        "type": "string",
                                        "format": "date"
                                    },
                                    "description": {
                                        "$id": "#/properties/academicExperiences/items/anyOf/0/properties/academicExperience/properties/description",
                                        "type": "string"
                                    }
                                },
                                "additionalProperties": true
                            }
                        },
                        "additionalProperties": true
                    }
                ]
            }
        }
    },
    "additionalProperties": true
}

=== ipallares/ipt-exporter/tests/exporter/application/services/exporter/input-data/cv1-v1.json
{
    "personalDetails": {
        "name": "Max",
        "surname": "Mustermann",
        "email": "max@mustermann.com",
        "phoneNumber": "555-55-55-55"
    },
    "coverLetter": {
        "text": "Lorem ipsum dolor sit amet..."
    },
    "workExperiences": [
        {
            "workExperience": {
                "companyName": "My Awesome Company",
                "position": "Senior developer",
                "startDate": "2016-11-15",
                "endDate": "2018-05-31",
                "description": "Taking care of refactoring the project to clean code and clean architectures."
            }
        },
        {
            "workExperience": {
                "companyName": "Another Cool Company",
                "position": "Senior - intermediate developer",
                "startDate": "2014-08-01",
                "endDate": "2018-10-01",
                "description": "Collaborating with IT Lead to design the project."
            }
        }
    ],
    "academicExperiences": [
        {
            "academicExperience": {
                "schoolName": "The IT University",
                "title": "Computer Engineer",
                "startDate": "2008-09-01",
                "endDate": "2014-06-30",
                "description": "Final Career Project on Machine Learning"
            }
        },
        {
            "academicExperience": {
                "schoolName": "The IT Institute",
                "title": "Technical Software Developer",
                "startDate": "2006-09-01",
                "endDate": "2008-06-30",
                "description": "6 months internship at 'Another Cool Company'"
            }
        }
    ]
}
